apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  # name must match the spec fields below, and be in the form: <plural>.<group>
  name: timebaseautoscaler.sre.exalab.co
spec:
  # group name to use for REST API: /apis/<group>/<version>
  group: sre.exalab.co
  # list of versions supported by this CustomResourceDefinition
  versions:
    - name: v1
      # Each version can be enabled/disabled by Served flag.
      served: true
      # One and only one version must be marked as the storage version.
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required:
              - deploymentName
              - scaleUpTime
              - scaleDownTime
              - scaleUpReplica
              - scaleDownReplica
              properties:
                deploymentName:
                  type: string
                scaleUpTime:
                  type: string
                scaleDownTime:
                  type: string
                scaleUpReplica:
                  type: integer
                scaleDownReplica:
                  type: integer
                waveOfScale:
                  type: integer
            status:
              type: object
              properties:
                set_replicas:
                  type: integer
                type:
                  type: string
                status:
                  type: string
                last_transition_time:
                  type: string
                  format: date-time
                message:
                  type: string
      subresources:
        status: {}
  # ei-ther Namespaced or Cluster
  scope: Namespaced
  names:
    # plural name to be used in the URL: /apis/<group>/<version>/<plural>
    plural: timebaseautoscaler
    # singular name to be used as an alias on the CLI and for display
    singular: timebaseautoscaler
    # kind is normally the CamelCased singular type. Your resource manifests use this.
    kind: TimeBaseAutoScaler
    # shortNames allow shorter string to match your resource on the CLI
    shortNames:
    - tbas