apiVersion: v1
kind: ServiceAccount
metadata:
  name: test
automountServiceAccountToken: true


---

apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: test
subjects:
- kind: ServiceAccount
  name: test # Name is case sensitive
  namespace: default
roleRef:
  kind: ClusterRole
  name: tbas-manager
  apiGroup: rbac.authorization.k8s.io

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: tbas-manager
rules:
- apiGroups: ["sre.exalab.co"]
  resources: ["timebaseautoscaler", "timebaseautoscaler/status"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments"]
  verbs: ["get", "list", "watch", "update", "patch"]